# Generated by Django 5.2.17 on 2026-08-17 17:04

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import pgvector.django
import pgvector.django.indexes
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        # pgvector extension (bundled with both the docker image and local brew
        # installs; this ensures it is enabled idempotently)
        pgvector.django.VectorExtension(),
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("messages", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.TextField(unique=True)),
                ("content_hash", models.CharField(max_length=64, unique=True)),
                ("broker", models.TextField(blank=True, default="")),
                ("published_date", models.DateField(blank=True, null=True)),
                (
                    "tickers",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("ticker_pages", models.JSONField(blank=True, default=dict)),
                ("title", models.TextField(blank=True, default="")),
                ("page_count", models.IntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("rendered", "Rendered"),
                            ("transcribed", "Transcribed"),
                            ("done", "Done"),
                            ("error", "Error"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("error", models.TextField(blank=True, default="")),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["broker", "published_date"],
                        name="research_do_broker_d15542_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page_number", models.IntegerField()),
                ("raw_text", models.TextField(blank=True, default="")),
                ("markdown", models.TextField(blank=True, default="")),
                ("has_visual", models.BooleanField(default=False)),
                ("png_path", models.TextField(blank=True, default="")),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(
                        blank=True, dimensions=1024, null=True
                    ),
                ),
                (
                    "search_vector",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.contrib.postgres.search.SearchVector(
                            "markdown", config="english"
                        ),
                        output_field=django.contrib.postgres.search.SearchVectorField(),
                    ),
                ),
                ("numeric_flags", models.JSONField(blank=True, null=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="research.document",
                    ),
                ),
            ],
            options={
                "indexes": [
                    pgvector.django.indexes.HnswIndex(
                        fields=["embedding"],
                        name="page_embedding_hnsw",
                        opclasses=["vector_cosine_ops"],
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["search_vector"], name="page_search_gin"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("document", "page_number"), name="uniq_doc_page"
                    )
                ],
            },
        ),
    ]
