# Generated by Django 5.2.17 on 2026-08-17, hand-edited to add the data fix.

from django.db import migrations, models


def empty_markdown_to_null(apps, schema_editor):
    """All pre-existing '' rows predate this migration and mean "not transcribed"
    → set to NULL so resume re-transcribes them. After this migration, '' means
    "transcribed and legitimately empty" (disclaimer pages)."""
    Page = apps.get_model("research", "Page")
    Page.objects.filter(markdown="").update(markdown=None)


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="markdown",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.RunPython(empty_markdown_to_null, migrations.RunPython.noop),
    ]
