# Generated by Django 5.2.17 on 2026-08-17, hand-edited to add the data fix.

from django.db import migrations, models


def empty_markdown_to_null(apps, schema_editor):
    """历史行的 '' 均产生于本迁移之前，语义是「未转录」→ 置 NULL 让 resume 重录。
    本迁移之后 '' 表示「已转录且合法为空」（免责声明页）。"""
    Page = apps.get_model("research", "Page")
    Page.objects.filter(markdown="").update(markdown=None)


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="markdown",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.RunPython(empty_markdown_to_null, migrations.RunPython.noop),
    ]
